### ISSUE TITLE
doesn't work for fargate only eks clusters

### ISSUE THREAD

**Issue by FernandoMiguel** [smpio/kubernator-vscode#2]
for EKS clusters with EC2, i can see all the cluster info.
but for fargate only clusters, this extension shows blank while the official kubernets shows all the available info.
any debug info i can provide to help debug this?

thanks in advance.

**Comment by nailgun** [comment]
I'm sorry, but I have no time to debug this issue and don't have any ideas about what it can be. I didn't work with fargate clusters. Maybe some RBAC issues. Internally kubernator runs `kubectl proxy`, so what you see with `kubectl`, you should see with kubernator. Maybe the default kubectl context is not what you want. In the latest update, I've added a feature to switch kubectl contexts. In the status bar, you can see the current context and click to switch it.

Also if nothing helps, feel free to open the project in vscode, place breakpoint here https://github.com/smpio/kubernator-vscode/blob/5e2adb1a6f0f7bdbc2a88847846b2ce563e65aef/src/kube/api.ts#L74 and hit F5. PRs are welcome! :)

**Comment by FernandoMiguel** [comment]
Seems to have a transient issue or bug on vscode... Eventually it started working without issues.
Thank you so much for the amazing work on this extension.

**Comment by nailgun** [comment]
> Thank you so much for the amazing work on this extension.

Thank you for your nice words.
